config/routes.rb
Rails.application.routes.draw do
 resources :movies do
 	  resources :reviews
 end
 
 root "movies#index"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  
  validates :title, :released_on, :duration, presence: true

  validates :description, length: { minimum: 25 }

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS,
    message: "must include G, PG-13, PG, R, or NC-17"
  }

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= 300000000').order('total_gross desc')
  end

  def self.flops
    where('total_gross < 10000000').order('total_gross asc')
  end

  def self.recently_added
    order('created_at desc').limit(3)
  end

  def flop?
    total_gross.blank? || total_gross < 50000000
  end
  
  def average_stars
    reviews.average(:stars)
  end
  
  def recent_reviews
    reviews.order('created_at desc').limit(2)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  
  validates :name, presence: true
  
  validates :comment, length: { minimum: 4 }
  
  STARS = [1, 2, 3, 4, 5]
  
  validates :stars, inclusion: { 
    in: STARS,
    message: "must be between 1 and 5"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end
  
private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    if @review.save
      redirect_to movie_reviews_path(@movie),
        notice: "Thanks for your review!"
    else
      render :new
    end
  end

  def destroy
    @review = @movie.reviews.find(params[:id])
    @review.destroy
    redirect_to movie_reviews_path(@movie), notice: "Review successfully deleted!"
  end

private

  def review_params
    params.require(:review).permit(:name, :comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def format_total_gross(movie)
		if movie.flop?
			content_tag(:strong, "Flop!")
		else
			number_to_currency(movie.total_gross)
		end
	end
 
 	def format_average_stars(movie)   
   		if movie.average_stars.nil?
     	content_tag(:strong, 'No reviews')
   		else
     	pluralize(number_with_precision(movie.average_stars, :precision => 1) , 'star')
   		end
 	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/_footer.html.erb
<footer id="page-footer">
  <p>
    Built by
    <%= link_to 'Shatavia Virgies','http://example(myblog).com' %>
    <br>
    <strong>Backend Engineer at 
    	<%= link_to 'The Iron Yard - Nashville Campus', 'http://theironyard.com/locations/nashville/' %>
    </strong>
  </p>
</footer>

app/views/application/_header.html.erb
<header id="page-header">
	<div id="masthead">
  		<h1>Zombie Flicks</h1>
  	</div>
</header>

app/views/application/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'Show All Movies', movies_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movieplex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= render 'header' %>


<div id="wrapper">
    <%= flash[:notice] %>
    <% if flash[:alert] %>
  <p class="flash alert">
    <%= flash[:alert] %>
  </p>
<% end %>

  <div id="container">
    <section id="sidebar">
		  <%= render 'sidebar' %>
	 </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>
		
	<%= render 'footer' %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render "shared/errors", object: @movie %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.text_field :rating, size: 4 %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_select :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.text_field :image_file_name, :placeholder => "JPG, GIF, PNG" %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_tag(movie.image_file_name, :height =>"400", :width => "350") %>
          <br>
          <br>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td> <%= movie.duration %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article>
  <header>
    <h1><%= @movie.title %></h1>
  </header>
    <%= image_tag(@movie.image_file_name, :height =>"600", :width => "500") %>
  <h2>Description</h2>
  <p>
    <%= @movie.description %>
  </p>
  <h3>Rating</h3>
  <p>
    <%= @movie.rating %>
  </p>
  <h3>Released On</h3>
  <p>
    <%= @movie.released_on %>
  </p>
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  <h3>Cast</h3>
<p>
  <%= @movie.cast %>
</p>

<h3>Director</h3>
<p>
  <%= @movie.director %>
</p>

<h3>Duration</h3>
<p>
  <%= @movie.duration %>
</p>
  
  <footer>
    <p>
      <%= link_to 'View All Reviews', movie_reviews_path(@movie) %>
    </p>
    <p>
      <%= link_to "Write Review", new_movie_review_path(@movie), 
                class: 'button ok review' %>
    </p>
    <nav>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@movie.title, @movie) %></h2>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= review.name %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to @movie.title, @movie %></h2>
</header>

<%= form_for [@movie, @review] do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>         
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
          <span class="star">
            <%= f.radio_button :stars, star %> <%= star %>
          </span>
        <% end %>     
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "Write your review here" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %> 
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>